### PR TITLE
Upgraded examples to match latest API

### LINKED ISSUE #4: Examples are broken: after logging in, still unauthorized.
Can't get anything but "sorry, you don't have access..."  Hmm.

### PR DESCRIPTION
**Pull request by jeluard**
Moved from `:config-auth` to `:credential-fn`. Fixes #4 and #7.

### CODE REVIEW

**Comment by trieloff** [comment]
I can confirm that it works at least with Facebook.

**Comment by felixflores** [comment]
+1

**Comment by rockBreaker** [comment]
+1 works with github

**Comment by felixflores** [comment]
+1

**Comment by ddellacosta** [comment]
Merged in, sorry for the slow response.

**Pull request merged**
